---

- name: Install Python 2.7.x
  raw: test -e /usr/bin/python || (apt -y update && apt install -y python)
  tags: init


- name: Only Ubuntu 16.04 is supported
  fail: msg="Unsupported OS - only Ubuntu 16.04 is supported"
  when: (ansible_distribution_release != 'xenial')


- apt: update_cache=yes
- apt: upgrade=dist


- name: Add the Python 3 PPA
  apt_repository: repo='ppa:deadsnakes/ppa' state=present


- name: Install base packages
  apt: name={{ item }} state=latest
  with_items:
    - git-core
    - build-essential
    - python-setuptools
    - python2.7-dev
    - python3-dev
    - python2.7
    - python3.5
    - python3.5-dev
    - python3.6
    - python3.6-dev
    - python-pip
    - virtualenvwrapper
    - libpq-dev
    - libjpeg-dev
    - zlib1g-dev
    - mosh
    - htop
    - httpie


- name: Install system-level python packages
  pip: name={{ item }} state=latest
  with_items:
    - httplib2
    - glances


- name: Add app user group
  group: name={{ app_name }} system=yes state=present


- name: Add app user
  user: name={{ app_name }} groups=staff,{{ app_name }} state=present append=yes shell=/bin/bash
