---

- apt: update_cache=yes
- apt: upgrade=dist


# - name: Add the Python 3 PPA
#   apt_repository: repo='ppa:deadsnakes/ppa' state=present


- name: Install base packages
  apt:
    pkg:
      - git-core
      - build-essential
      - python-setuptools
      - python3.8
      - python3.8-dev
      - virtualenvwrapper
      - libpq-dev
      - libjpeg-dev
      - zlib1g-dev
      - htop


- name: Add app user group
  group:
    name: "{{ app_name }}"
    system: yes
    state: present


- name: Add app user
  user:
    name: "{{ app_name }}"
    groups:
      - "{{ app_name }}"
    state: present
    append: yes
    shell: /bin/bash


- name: Install acme.sh
  shell: curl https://get.acme.sh | sh -s email=brenton@brntn.me
  args:
    warn: no


- name: Make directories for application
  file: path={{ item }} state=directory
  with_items:
    - /srv/www/{{ app_name }}
    - /srv/www/{{ app_name }}/static
    - /srv/www/{{ app_name }}/logs
    - /srv/www/{{ app_name }}/code
    - /srv/www/{{ app_name }}/media
  tags: deploy