---

- apt: update_cache=yes
- apt: upgrade=dist


- name: Add the Python 3 PPA
  apt_repository: repo='ppa:deadsnakes/ppa' state=present


- name: Install base packages
  apt:
    pkg:
      - git-core
      - build-essential
      - python-setuptools
      - python3.8
      - python3.8-dev
      - virtualenvwrapper
      - libpq-dev
      - libjpeg-dev
      - zlib1g-dev
      - htop


- name: Install snap package for certbot
  snap:
    name: certbot
    classic: yes


- name: Create symlink for certbot
  file:
    src: /snap/bin/certbot
    dest: /usr/bin/certbot
    state: link


- name: Add app user group
  group:
    name: "{{ app_name }}"
    system: yes
    state: present


- name: Add app user
  user:
    name: "{{ app_name }}"
    groups:
      - "{{ app_name }}"
    state: present
    append: yes
    shell: /bin/bash
