---

- apt: update_cache=yes
- apt: upgrade=dist


- name: Install base packages
  apt:
    pkg:
      - build-essential
      - python3
      - python3-pip
      - virtualenvwrapper
      - libpq-dev
      - libjpeg-dev
      - zlib1g-dev


- name: Add app user group
  group:
    name: "{{ app_name }}"
    system: yes
    state: present


- name: Add app user
  user:
    name: "{{ app_name }}"
    groups:
      - "{{ app_name }}"
    state: present
    append: yes
    shell: /bin/bash


- name: Install acme.sh
  shell: curl https://get.acme.sh | sh -s email={{ certbot_email }}
  args:
    warn: no


- name: Make directories for application
  file: path={{ item }} state=directory
  with_items:
    - /srv/www/{{ app_name }}
    - /srv/www/{{ app_name }}/static
    - /srv/www/{{ app_name }}/logs
    - /srv/www/{{ app_name }}/code
    - /srv/www/{{ app_name }}/media
