---

- name: Add chris lea's redis apt repository
  apt_repository: repo='ppa:chris-lea/redis-server' state=present


- name: Install redis
  apt: name=redis-server state=latest


- name: Start / restart redis
  service: name=redis-server state=restarted
