---

- apt: name={{ item }} state=latest
  with_items:
    - libfreetype6
    - libfreetype6-dev
    - fontconfig

- shell: ls /usr/local/bin/
  register: bin_dir

- get_url:
    url: "{{ phantomjs_url }}"
    dest: "/tmp/phantomjs.tar.bz2"
    force: true
  when: bin_dir.stdout.find("phantomjs") == -1

# extract and copy in one step --strip-components=2 takes care that we don't copy the entire path just the bin file
- shell: "cd /tmp && tar xvjf /tmp/phantomjs.tar.bz2 -C /usr/local/bin/ --overwrite --wildcards '**/bin/phantomjs' --strip-components=2"
  when: bin_dir.stdout.find("phantomjs") == -1

- file:
    path: /usr/local/bin/phantomjs
    state: file
    mode: 0755
