---

- apt: update_cache=yes


- name: Install postgresql
  apt: name={{ item }} state=latest
  with_items:
    - postgresql
    - postgresql-client
    - python-psycopg2
    - python3-psycopg2


- name: Ensure postgres is running
  service: name=postgresql state=started


- name: Create our database
  postgresql_db: name={{ app_name }}
  become: yes
  become_user: postgres
  tags: deploy


- name: Create the database user for this app
  postgresql_user: name={{ app_name }} db={{ app_name }} password='{{ db_password }}'
  become: yes
  become_user: postgres
  tags: deploy
