---

- name: Add app-celery.sh file
  template: src=celery.sh.j2 dest=/srv/www/{{ app_name }}/{{ app_name }}-celery.sh owner={{ app_name }} group={{ app_name }} mode=ug+x
  tags: deploy


- name: Systemd config
  template: src=celery.systemd.service.j2 dest=/etc/systemd/system/{{ service_name }}-celery.service
  tags: deploy


- name: Restart celery (and ensure it's enabled)
  service: name={{ service_name }}-celery state=started enabled=yes
  tags: deploy
